name: Continuous Deployment (Prod) (Backend)

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production



    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3   
      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}


      - name: Debug – list repo files
        run: |
          echo "Current path:"
          pwd
          echo "Contents of repo root:"
          ls -al
          echo "Contents of ./server directory:"
          ls -al ./server

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./server
          file: ./server/Dockerfile
          push: true
          tags: |
            rohandasari/backend:latest
            rohandasari/backend:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
